from __future__ import annotations

import torch
from mjlab.utils.lab_api.math import matrix_from_quat

from . import commands as _commands
from .kneel_motion_library import KneelSparseWholeBodyMotionLibrary


_PATCHED = False


def _collapse_primary_contact(found: torch.Tensor) -> torch.Tensor:
  mask = found > 0
  while mask.ndim > 2:
    mask = torch.any(mask, dim=-1)
  if mask.ndim == 1:
    mask = mask[:, None]
  return mask


def _single_sensor_contact(command, sensor_name: str) -> torch.Tensor:
  try:
    sensor = command._env.scene[sensor_name]
  except Exception:
    return torch.zeros(
      command.num_envs, dtype=torch.bool, device=command.device
    )
  found = sensor.data.found
  if found is None:
    return torch.zeros(
      command.num_envs, dtype=torch.bool, device=command.device
    )
  mask = found > 0
  while mask.ndim > 1:
    mask = torch.any(mask, dim=-1)
  return mask


def activate_kneel_extensions() -> None:
  """Install dataset/contact extensions without rewriting the base teleop task."""
  global _PATCHED
  if _PATCHED:
    return
  _PATCHED = True

  # SparseWholeBodyCommand resolves this module-global at runtime in __init__.
  # Swapping it here preserves the original command implementation while giving
  # every teleop task backward-compatible support for the new synthesized data.
  _commands.SparseWholeBodyMotionLibrary = KneelSparseWholeBodyMotionLibrary

  cls = _commands.SparseWholeBodyCommand
  original_init = cls.__init__
  original_update_npz = cls._update_npz_targets
  original_update_metrics = cls._update_metrics
  original_finalize = cls._finalize_episode_metrics
  original_clear = cls._clear_episode_accumulators
  original_balance = cls.compute_com_support_margin

  def patched_init(self, *args, **kwargs):
    original_init(self, *args, **kwargs)
    self._npz_phase = torch.zeros(
      self.num_envs, dtype=torch.long, device=self.device
    )
    self._npz_wrist_tracking_weight_scale = torch.ones(
      self.num_envs, dtype=torch.float32, device=self.device
    )
    if hasattr(self.motion, "sample_aux"):
      phase, weight = self.motion.sample_aux(self.motion_ids, self.command_time)
      self._npz_phase[:] = phase
      self._npz_wrist_tracking_weight_scale[:] = weight

    self._episode_left_knee_contact_sum = torch.zeros(
      self.num_envs, dtype=torch.float32, device=self.device
    )
    self._episode_right_knee_contact_sum = torch.zeros_like(
      self._episode_left_knee_contact_sum
    )
    self._episode_any_knee_contact_sum = torch.zeros_like(
      self._episode_left_knee_contact_sum
    )
    self._episode_bilateral_knee_contact_sum = torch.zeros_like(
      self._episode_left_knee_contact_sum
    )

    for name in (
      "contact/left_knee",
      "contact/right_knee",
      "contact/any_knee",
      "episode/left_knee_contact_fraction",
      "episode/right_knee_contact_fraction",
      "episode/any_knee_contact_fraction",
      "episode/bilateral_knee_contact_fraction",
      "command/phase",
      "command/wrist_task_weight",
    ):
      self.metrics[name] = torch.zeros(self.num_envs, device=self.device)

    if self.cfg.style_mode == "descriptor":
      for name in (
        "style_task_gate_raw",
        "style_shape_balance_gate",
      ):
        self.metrics[name] = torch.zeros(self.num_envs, device=self.device)

  def patched_update_npz_targets(self, env_ids: torch.Tensor):
    original_update_npz(self, env_ids)
    if (
      len(env_ids) > 0
      and hasattr(self, "_npz_phase")
      and hasattr(self.motion, "sample_aux")
    ):
      phase, weight = self.motion.sample_aux(
        self.motion_ids[env_ids], self.command_time[env_ids]
      )
      self._npz_phase[env_ids] = phase
      self._npz_wrist_tracking_weight_scale[env_ids] = weight

  def current_phase(self) -> torch.Tensor:
    return self._npz_phase

  def wrist_task_weight_scale(self) -> torch.Tensor:
    # Warm-up/recovery are generated by the environment rather than the source
    # NPZ, so retain full tracking strength outside recorded-motion playback.
    return torch.where(
      self.motion_tracking_active,
      self._npz_wrist_tracking_weight_scale,
      torch.ones_like(self._npz_wrist_tracking_weight_scale),
    )

  def knee_contact_masks(self) -> tuple[torch.Tensor, torch.Tensor]:
    return (
      _single_sensor_contact(self, "left_knee_ground_contact"),
      _single_sensor_contact(self, "right_knee_ground_contact"),
    )

  def patched_update_metrics(self):
    original_update_metrics(self)
    left, right = knee_contact_masks(self)
    any_knee = left | right
    bilateral = left & right
    self.metrics["contact/left_knee"] = left.to(torch.float32)
    self.metrics["contact/right_knee"] = right.to(torch.float32)
    self.metrics["contact/any_knee"] = any_knee.to(torch.float32)
    self.metrics["command/phase"] = self.current_phase.to(torch.float32)
    self.metrics["command/wrist_task_weight"] = self.wrist_task_weight_scale

    active = self.motion_tracking_active.to(torch.float32)
    self._episode_left_knee_contact_sum += left.to(torch.float32) * active
    self._episode_right_knee_contact_sum += right.to(torch.float32) * active
    self._episode_any_knee_contact_sum += any_knee.to(torch.float32) * active
    self._episode_bilateral_knee_contact_sum += bilateral.to(torch.float32) * active

  def patched_finalize(self, env_ids: torch.Tensor):
    original_finalize(self, env_ids)
    if len(env_ids) == 0:
      return
    steps = self._episode_tracking_steps[env_ids]
    denom = torch.clamp(steps, min=1).to(torch.float32)
    for key, value in (
      ("episode/left_knee_contact_fraction", self._episode_left_knee_contact_sum),
      ("episode/right_knee_contact_fraction", self._episode_right_knee_contact_sum),
      ("episode/any_knee_contact_fraction", self._episode_any_knee_contact_sum),
      (
        "episode/bilateral_knee_contact_fraction",
        self._episode_bilateral_knee_contact_sum,
      ),
    ):
      fraction = value[env_ids] / denom
      fraction = torch.where(
        steps > 0, fraction, torch.zeros_like(fraction)
      )
      self.metrics[key][env_ids] = fraction

  def patched_clear(self, env_ids: torch.Tensor):
    original_clear(self, env_ids)
    if len(env_ids) == 0:
      return
    self._episode_left_knee_contact_sum[env_ids] = 0.0
    self._episode_right_knee_contact_sum[env_ids] = 0.0
    self._episode_any_knee_contact_sum[env_ids] = 0.0
    self._episode_bilateral_knee_contact_sum[env_ids] = 0.0

  def knee_aware_com_support_margin(self) -> torch.Tensor:
    """Foot support polygon extended by contacting knee/shin patches.

    Static-kneel training keeps balance_mode=off by default.  This function is
    nevertheless installed now so later balance ablations do not classify a
    physically stable foot+shin/knee support configuration as unsupported.
    """
    if self.cfg.balance_mode == "off":
      return torch.zeros(self.num_envs, device=self.device)

    try:
      left_sensor = self._env.scene["left_knee_ground_contact"]
      right_sensor = self._env.scene["right_knee_ground_contact"]
    except Exception:
      return original_balance(self)

    root_body_id = self.robot.data.indexing.root_body_id
    com_xy = self.robot.data.data.subtree_com[:, root_body_id, :2]

    foot_pos = self.robot.data.body_link_pos_w[:, self.balance_foot_indices]
    foot_quat = self.robot.data.body_link_quat_w[:, self.balance_foot_indices]
    foot_rotation = matrix_from_quat(foot_quat)
    x_min, x_max = self.cfg.balance_foot_x_range
    y_min, y_max = self.cfg.balance_foot_y_range
    foot_corners_b = torch.tensor(
      (
        (x_min, y_min, 0.0),
        (x_max, y_min, 0.0),
        (x_max, y_max, 0.0),
        (x_min, y_max, 0.0),
      ),
      dtype=foot_pos.dtype,
      device=self.device,
    )
    foot_corners_w = foot_pos[:, :, None, :] + torch.einsum(
      "bfij,kj->bfki", foot_rotation, foot_corners_b
    )
    foot_points = foot_corners_w[..., :2].reshape(self.num_envs, 8, 2)

    foot_found = self._env.scene[
      self.cfg.balance_contact_sensor_name
    ].data.found
    if foot_found is None:
      return original_balance(self)
    foot_contact = _collapse_primary_contact(foot_found)
    if foot_contact.shape[1] != 2:
      return original_balance(self)
    foot_valid = foot_contact.repeat_interleave(4, dim=1)

    left_contact = _single_sensor_contact(self, "left_knee_ground_contact")
    right_contact = _single_sensor_contact(self, "right_knee_ground_contact")
    knee_contact = torch.stack((left_contact, right_contact), dim=1)
    knee_pos = self.robot.data.body_link_pos_w[:, (
      self.style_left_knee_index,
      self.style_right_knee_index,
    ), :2]

    # Small world-XY support patches are deliberately conservative.  The stock
    # G1 collision model represents knee support using shin/linkage capsules,
    # not a literal planar patella geom.
    knee_offsets = torch.tensor(
      (
        (-0.05, -0.04),
        (0.05, -0.04),
        (0.05, 0.04),
        (-0.05, 0.04),
      ),
      dtype=knee_pos.dtype,
      device=self.device,
    )
    knee_points = (
      knee_pos[:, :, None, :] + knee_offsets[None, None, :, :]
    ).reshape(self.num_envs, 8, 2)
    knee_valid = knee_contact.repeat_interleave(4, dim=1)

    points = torch.cat((foot_points, knee_points), dim=1)
    point_valid = torch.cat((foot_valid, knee_valid), dim=1)

    start = points[:, :, None, :]
    edge = points[:, None, :, :] - start
    edge_len_sq = torch.sum(torch.square(edge), dim=-1)
    other = points[:, None, None, :, :] - start[:, :, :, None, :]
    cross_all = (
      edge[..., None, 0] * other[..., 1]
      - edge[..., None, 1] * other[..., 0]
    )
    all_points_left = torch.all(
      (~point_valid[:, None, None, :]) | (cross_all >= -1.0e-6), dim=-1
    )
    edge_valid = (
      point_valid[:, :, None]
      & point_valid[:, None, :]
      & (edge_len_sq > 1.0e-12)
      & all_points_left
    )

    com_from_start = com_xy[:, None, :] - points
    signed_edge_distance = (
      edge[..., 0] * com_from_start[:, :, None, 1]
      - edge[..., 1] * com_from_start[:, :, None, 0]
    ) / torch.sqrt(edge_len_sq.clamp_min(1.0e-12))
    inside_margin = signed_edge_distance.masked_fill(
      ~edge_valid, torch.inf
    ).amin(dim=(1, 2))
    inside = inside_margin >= 0.0

    projection = torch.sum(
      com_from_start[:, :, None, :] * edge, dim=-1
    ) / edge_len_sq.clamp_min(1.0e-12)
    projection = projection.clamp(0.0, 1.0)
    closest = start + projection[..., None] * edge
    segment_distance = torch.linalg.vector_norm(
      com_xy[:, None, None, :] - closest, dim=-1
    ).masked_fill(~edge_valid, torch.inf).amin(dim=(1, 2))

    has_support = edge_valid.any(dim=(1, 2))
    margin = torch.where(inside, inside_margin, -segment_distance)
    return torch.where(
      has_support, margin, torch.full_like(margin, -0.10)
    )

  cls.__init__ = patched_init
  cls._update_npz_targets = patched_update_npz_targets
  cls.current_phase = property(current_phase)
  cls.wrist_task_weight_scale = property(wrist_task_weight_scale)
  cls.knee_contact_masks = knee_contact_masks
  cls._update_metrics = patched_update_metrics
  cls._finalize_episode_metrics = patched_finalize
  cls._clear_episode_accumulators = patched_clear
  cls.compute_com_support_margin = knee_aware_com_support_margin
